source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!
platform :ios, '8.0'

project 'LongPressMoveCellDemo.xcodeproj' 

target 'LongPressMoveCellDemo' do 
    
    pod 'Masonry' 
    pod 'MBProgressHUD'
    pod 'Mantle'
    
end
